[project]
name = "cs-checklist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "openpyxl>=3.1.2",
    "firebase-admin>=6.4.0",
    "python-dotenv>=1.0.0"
]
